# .github/workflows/release.yml

name: Create Release, Build and Deploy

on:
  push:
    tags:
      - 'v*.*.*'

env:
  # Ayarları merkezi bir yerden yönetelim
  GCP_FIREWALL_RULE_PREFIX: 'allow-ssh-github-actions' # Kuralların ön eki
  GCP_NETWORK_TAG: 'sip-server'

jobs:
  # --- Build ve Docker adımları aynı kalıyor ---
  create_release:
    # ... (İÇERİK DEĞİŞMEDİ) ...
  build_binaries:
    # ... (İÇERİK DEĞİŞMEDİ) ...
  build_and_publish_docker:
    # ... (İÇERİK DEĞİŞMEDİ) ...

  # --- Dağıtım Adımı API Limitlerini Aşacak Şekilde Yeniden Yazıldı ---
  deploy_to_server:
    name: Deploy to SIP Server
    needs: build_binaries
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Get and Chunk GitHub Actions IPs'
        id: get_ips
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          # Tüm IP'leri al
          curl -s https://api.github.com/meta | jq -r '.actions[]' > all_ips.txt
          # IP'leri 250'lik parçalara böl ve her parçayı ayrı bir dosyaya yaz
          split -l 250 all_ips.txt ip_chunk_
          # Kaç tane dosya oluştuğunu say ve bir sonraki adım için sakla
          echo "chunk_count=$(ls ip_chunk_* | wc -l)" >> "$GITHUB_OUTPUT"

      - name: 'Create or Update GCP Firewall Rules'
        run: |
          # Önceki adımdan kaç parça olduğunu al
          CHUNK_COUNT=${{ steps.get_ips.outputs.chunk_count }}
          
          # Her bir IP parçası dosyası için döngü başlat
          for i in $(seq 0 $(($CHUNK_COUNT - 1))); do
            # Dosya adını ve kural adını belirle
            CHUNK_FILE=$(printf "ip_chunk_%s" $(printf "%02d" $i | awk '{print substr("abcdefghijklmnopqrstuvwxyz", $1+1, 1) substr("abcdefghijklmnopqrstuvwxyz", $1+1, 1)}'))
            RULE_NAME="${{ env.GCP_FIREWALL_RULE_PREFIX }}-${i}"
            
            # IP'leri dosyadan oku ve virgülle birleştir
            SOURCE_RANGES=$(paste -sd, $CHUNK_FILE)
            
            echo "Processing rule: $RULE_NAME with $(wc -l < $CHUNK_FILE) IPs..."
            
            # Kuralın zaten var olup olmadığını kontrol et
            if gcloud compute firewall-rules describe $RULE_NAME --project=${{ secrets.GCP_PROJECT_ID }} &> /dev/null; then
              echo "Firewall rule $RULE_NAME found. Updating..."
              gcloud compute firewall-rules update $RULE_NAME \
                --project=${{ secrets.GCP_PROJECT_ID }} \
                --source-ranges="$SOURCE_RANGES"
            else
              echo "Firewall rule $RULE_NAME not found. Creating..."
              gcloud compute firewall-rules create $RULE_NAME \
                --project=${{ secrets.GCP_PROJECT_ID }} \
                --network=default \
                --action=ALLOW \
                --direction=INGRESS \
                --rules=tcp:22 \
                --target-tags=${{ env.GCP_NETWORK_TAG }} \
                --source-ranges="$SOURCE_RANGES"
            fi
          done
          
          # Gereksiz eski kuralları temizle
          # Tüm mevcut kuralları listele
          EXISTING_RULES=$(gcloud compute firewall-rules list --project=${{ secrets.GCP_PROJECT_ID }} --filter="name~'^${{ env.GCP_FIREWALL_RULE_PREFIX }}-'" --format="value(name)")
          for RULE in $EXISTING_RULES; do
            # Kural adından sıra numarasını al
            INDEX=$(echo $RULE | sed 's/.*-//')
            if [ $INDEX -ge $CHUNK_COUNT ]; then
              echo "Deleting obsolete firewall rule: $RULE"
              gcloud compute firewall-rules delete $RULE --project=${{ secrets.GCP_PROJECT_ID }} --quiet
            fi
          done

      - name: 'Deploy binary via SSH'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ~/app/sentiric-sip
            cd ~/app/sentiric-sip
            pkill -f sentiric-sip-core-service || true
            wget -q https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/sentiric-sip-core-service-linux-x86_64.tar.gz -O release.tar.gz
            tar -xzvf release.tar.gz
            chmod +x sentiric-sip-core-service
            export SERVER_IP=${{ secrets.SSH_HOST }}
            nohup ./sentiric-sip-core-service > service.log 2>&1 &